apiVersion: 1

datasources:
  - name: Prometheus-Catalog
    type: prometheus
    uid: prometheus-catalog
    access: proxy
    url: http://prometheus_catalog:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST