DEFAULT_SKIP = 0
DEFAULT_LIMIT = 100

CATEGORY_SKIP = 0
CATEGORY_LIMIT = 100
CATEGORY_NAME_MIN_LENGTH = 1
CATEGORY_NAME_MAX_LENGTH = 64

PRODUCT_SKIP = 0
PRODUCT_LIMIT = 100
PRODUCT_NAME_MIN_LENGTH = 1
PRODUCT_NAME_MAX_LENGTH = 64
PRODUCT_DESCRIPTION_MIN_LENGTH = 1
PRODUCT_DESCRIPTION_MAX_LENGTH = 1000
PRODUCT_PRICE_MAX_DIGITS = 10
PRODUCT_PRICE_MIN_VALUE = 0
PRODUCT_PRICE_DECIMAL_PLACES = 2

CACHE_TTL = 60 * 60